server:
  port: 8888
spring:
  data:
    mongodb:
      ghotel: 
        host: localhost
        port: 27017
        database: g
      oss: 
        host: localhost
        port: 27017
        database: o
  mvc:
    static-path-pattern: /cmc/** 
  resources:
    static-locations: /static/
    
logging:
  level:
    root: info